-- Avalix - migration 0014: corrige acentuacao dos nomes dos exercicios globais.
-- O seed 0008 foi gravado sem acentos; isto corrige as linhas ja existentes
-- (org_id null) por UPDATE, casando pelo nome antigo. Nao reinsere (preserva os
-- ids referenciados pelos planos). Idempotente: rodar de novo nao reacha nada.

update public.exercises set name = 'Supino reto na máquina' where org_id is null and name = 'Supino reto na maquina';
update public.exercises set name = 'Supino inclinado na máquina' where org_id is null and name = 'Supino inclinado na maquina';
update public.exercises set name = 'Chest press na máquina' where org_id is null and name = 'Chest press na maquina';
update public.exercises set name = 'Crucifixo na máquina (peck deck)' where org_id is null and name = 'Crucifixo na maquina (peck deck)';
update public.exercises set name = 'Flexão de braços' where org_id is null and name = 'Flexao de bracos';
update public.exercises set name = 'Flexão de braços inclinada' where org_id is null and name = 'Flexao de bracos inclinada';
update public.exercises set name = 'Flexão de braços declinada' where org_id is null and name = 'Flexao de bracos declinada';
update public.exercises set name = 'Flexão na suspensão (TRX)' where org_id is null and name = 'Flexao na suspensao (TRX)';
update public.exercises set name = 'Barra fixa assistida na máquina' where org_id is null and name = 'Barra fixa assistida na maquina';
update public.exercises set name = 'Puxada pegada neutra (triângulo)' where org_id is null and name = 'Puxada pegada neutra (triangulo)';
update public.exercises set name = 'Pulldown na máquina' where org_id is null and name = 'Pulldown na maquina';
update public.exercises set name = 'Pullover na máquina' where org_id is null and name = 'Pullover na maquina';
update public.exercises set name = 'Remada baixa no cabo (triângulo)' where org_id is null and name = 'Remada baixa no cabo (triangulo)';
update public.exercises set name = 'Remada na máquina (apoio no peito)' where org_id is null and name = 'Remada na maquina (apoio no peito)';
update public.exercises set name = 'Remada na suspensão (TRX)' where org_id is null and name = 'Remada na suspensao (TRX)';
update public.exercises set name = 'Remada alta na máquina (high row)' where org_id is null and name = 'Remada alta na maquina (high row)';
update public.exercises set name = 'Remada alta no cabo para o pescoço' where org_id is null and name = 'Remada alta no cabo para o pescoco';
update public.exercises set name = 'Encolhimento na máquina' where org_id is null and name = 'Encolhimento na maquina';
update public.exercises set name = 'Desenvolvimento militar com barra (em pé)' where org_id is null and name = 'Desenvolvimento militar com barra (em pe)';
update public.exercises set name = 'Desenvolvimento na máquina' where org_id is null and name = 'Desenvolvimento na maquina';
update public.exercises set name = 'Elevação frontal com halteres' where org_id is null and name = 'Elevacao frontal com halteres';
update public.exercises set name = 'Elevação frontal com barra' where org_id is null and name = 'Elevacao frontal com barra';
update public.exercises set name = 'Elevação frontal no cabo' where org_id is null and name = 'Elevacao frontal no cabo';
update public.exercises set name = 'Elevação frontal com anilha' where org_id is null and name = 'Elevacao frontal com anilha';
update public.exercises set name = 'Elevação lateral com halteres' where org_id is null and name = 'Elevacao lateral com halteres';
update public.exercises set name = 'Elevação lateral no cabo' where org_id is null and name = 'Elevacao lateral no cabo';
update public.exercises set name = 'Elevação lateral na máquina' where org_id is null and name = 'Elevacao lateral na maquina';
update public.exercises set name = 'Elevação lateral deitado de lado' where org_id is null and name = 'Elevacao lateral deitado de lado';
update public.exercises set name = 'Elevação lateral com faixa' where org_id is null and name = 'Elevacao lateral com faixa';
update public.exercises set name = 'Crucifixo invertido curvado (em pé)' where org_id is null and name = 'Crucifixo invertido curvado (em pe)';
update public.exercises set name = 'Crucifixo invertido na máquina (reverse peck)' where org_id is null and name = 'Crucifixo invertido na maquina (reverse peck)';
update public.exercises set name = 'Rosca simultânea com halteres' where org_id is null and name = 'Rosca simultanea com halteres';
update public.exercises set name = 'Rosca Scott na máquina' where org_id is null and name = 'Rosca Scott na maquina';
update public.exercises set name = 'Tríceps na polia (barra reta)' where org_id is null and name = 'Triceps na polia (barra reta)';
update public.exercises set name = 'Tríceps na polia (corda)' where org_id is null and name = 'Triceps na polia (corda)';
update public.exercises set name = 'Tríceps na polia (barra V)' where org_id is null and name = 'Triceps na polia (barra V)';
update public.exercises set name = 'Tríceps testa com barra W' where org_id is null and name = 'Triceps testa com barra W';
update public.exercises set name = 'Tríceps testa na barra reta' where org_id is null and name = 'Triceps testa na barra reta';
update public.exercises set name = 'Tríceps testa com halteres' where org_id is null and name = 'Triceps testa com halteres';
update public.exercises set name = 'Tríceps francês com halter' where org_id is null and name = 'Triceps frances com halter';
update public.exercises set name = 'Tríceps francês na corda (cabo)' where org_id is null and name = 'Triceps frances na corda (cabo)';
update public.exercises set name = 'Extensão de tríceps acima da cabeça na máquina' where org_id is null and name = 'Extensao de triceps acima da cabeca na maquina';
update public.exercises set name = 'Tríceps coice com halter' where org_id is null and name = 'Triceps coice com halter';
update public.exercises set name = 'Tríceps coice no cabo' where org_id is null and name = 'Triceps coice no cabo';
update public.exercises set name = 'Extensão de tríceps unilateral no cabo' where org_id is null and name = 'Extensao de triceps unilateral no cabo';
update public.exercises set name = 'Tríceps na máquina' where org_id is null and name = 'Triceps na maquina';
update public.exercises set name = 'Tríceps com faixa' where org_id is null and name = 'Triceps com faixa';
update public.exercises set name = 'Mergulho nas paralelas (tríceps)' where org_id is null and name = 'Mergulho nas paralelas (triceps)';
update public.exercises set name = 'Flexão diamante' where org_id is null and name = 'Flexao diamante';
update public.exercises set name = 'Sustentação com halteres (hold)' where org_id is null and name = 'Sustentacao com halteres (hold)';
update public.exercises set name = 'Abdominal na máquina' where org_id is null and name = 'Abdominal na maquina';
update public.exercises set name = 'Elevação de pernas suspenso' where org_id is null and name = 'Elevacao de pernas suspenso';
update public.exercises set name = 'Elevação de joelhos na cadeira romana' where org_id is null and name = 'Elevacao de joelhos na cadeira romana';
update public.exercises set name = 'Elevação de pernas no solo' where org_id is null and name = 'Elevacao de pernas no solo';
update public.exercises set name = 'Prancha na suspensão (TRX)' where org_id is null and name = 'Prancha na suspensao (TRX)';
update public.exercises set name = 'Rotação russa (russian twist)' where org_id is null and name = 'Rotacao russa (russian twist)';
update public.exercises set name = 'Flexão lateral com halter' where org_id is null and name = 'Flexao lateral com halter';
update public.exercises set name = 'Flexão lateral no cabo' where org_id is null and name = 'Flexao lateral no cabo';
update public.exercises set name = 'Hiperextensão lombar (banco romano)' where org_id is null and name = 'Hiperextensao lombar (banco romano)';
update public.exercises set name = 'Hiperextensão com anilha' where org_id is null and name = 'Hiperextensao com anilha';
update public.exercises set name = 'Extensão lombar na máquina' where org_id is null and name = 'Extensao lombar na maquina';
update public.exercises set name = 'Agachamento sumô com barra' where org_id is null and name = 'Agachamento sumo com barra';
update public.exercises set name = 'Agachamento búlgaro com halteres' where org_id is null and name = 'Agachamento bulgaro com halteres';
update public.exercises set name = 'Agachamento búlgaro no Smith' where org_id is null and name = 'Agachamento bulgaro no Smith';
update public.exercises set name = 'Avanço no Smith' where org_id is null and name = 'Avanco no Smith';
update public.exercises set name = 'Levantamento terra sumô' where org_id is null and name = 'Levantamento terra sumo';
update public.exercises set name = 'Good morning (ênfase posterior)' where org_id is null and name = 'Good morning (enfase posterior)';
update public.exercises set name = 'Flexora em pé unilateral' where org_id is null and name = 'Flexora em pe unilateral';
update public.exercises set name = 'Flexão nórdica (Nordic curl)' where org_id is null and name = 'Flexao nordica (Nordic curl)';
update public.exercises set name = 'Elevação pélvica com barra (hip thrust)' where org_id is null and name = 'Elevacao pelvica com barra (hip thrust)';
update public.exercises set name = 'Hip thrust na máquina' where org_id is null and name = 'Hip thrust na maquina';
update public.exercises set name = 'Ponte de glúteo (glute bridge)' where org_id is null and name = 'Ponte de gluteo (glute bridge)';
update public.exercises set name = 'Elevação pélvica (peso corporal)' where org_id is null and name = 'Elevacao pelvica (peso corporal)';
update public.exercises set name = 'Coice de glúteo no cabo' where org_id is null and name = 'Coice de gluteo no cabo';
update public.exercises set name = 'Coice de glúteo na máquina' where org_id is null and name = 'Coice de gluteo na maquina';
update public.exercises set name = 'Coice de glúteo com faixa' where org_id is null and name = 'Coice de gluteo com faixa';
update public.exercises set name = 'Step-up alto (ênfase glúteo)' where org_id is null and name = 'Step-up alto (enfase gluteo)';
update public.exercises set name = 'Adução de quadril no cabo' where org_id is null and name = 'Aducao de quadril no cabo';
update public.exercises set name = 'Adução com faixa' where org_id is null and name = 'Aducao com faixa';
update public.exercises set name = 'Abdução de quadril no cabo' where org_id is null and name = 'Abducao de quadril no cabo';
update public.exercises set name = 'Abdução em pé com faixa' where org_id is null and name = 'Abducao em pe com faixa';
update public.exercises set name = 'Abdução deitado de lado' where org_id is null and name = 'Abducao deitado de lado';
update public.exercises set name = 'Panturrilha em pé na máquina' where org_id is null and name = 'Panturrilha em pe na maquina';
update public.exercises set name = 'Panturrilha sentado na máquina' where org_id is null and name = 'Panturrilha sentado na maquina';
update public.exercises set name = 'Panturrilha em pé com halteres' where org_id is null and name = 'Panturrilha em pe com halteres';
update public.exercises set name = 'Panturrilha em pé com barra' where org_id is null and name = 'Panturrilha em pe com barra';
update public.exercises set name = 'Flexão de pescoço com anilha' where org_id is null and name = 'Flexao de pescoco com anilha';
update public.exercises set name = 'Extensão de pescoço com anilha' where org_id is null and name = 'Extensao de pescoco com anilha';
update public.exercises set name = 'Neck curl na máquina' where org_id is null and name = 'Neck curl na maquina';
update public.exercises set name = 'Flexão lateral de pescoço com faixa' where org_id is null and name = 'Flexao lateral de pescoco com faixa';
update public.exercises set name = 'Empurrar trenó (prowler)' where org_id is null and name = 'Empurrar treno (prowler)';
update public.exercises set name = 'Puxar trenó (sled pull)' where org_id is null and name = 'Puxar treno (sled pull)';
